### PR TITLE
Joseph geolocate

### PR DESCRIPTION
**Pull request by JoePark1993**
Players are now able to see their location and validate that they are in the correct arena location.
Players are able to be assigned to a game room and have a field for their location.
Files of concern:
waitingroom.js
createroom.js
game.js

### CODE REVIEW

**Comment by JoePark1993** [comment]
@jkwon045 @ChristianPomales @vabdurahmanov Hey guys check it out!

**Comment by JoePark1993** [comment]
This only requires a code review since it's already merged. Anything that you guys are concerned about would be good input!

**Comment by ChristianPomales** [comment]
Looks good! @vabdurahmanov what do you think?

**Comment by jkwon045** [comment]
It looks good!

**Pull request closed without merging**
