### PR TITLE
Joseph geolocate

### PR DESCRIPTION
**Pull request by JoePark1993**
I've integrated the google maps into the `createRoom.js`. States are now set for each player. You should be able to gather their lat,lng,radius,ID ...etc. The only file that I touched is in `createRoom.js`

### CODE REVIEW

**Comment by vabdurahmanov** [comment]
Nice work! Looks good

**Comment by JoePark1993** [comment]
@ChristianPomales @jkwon045 @vabdurahmanov Fixed current merge conflicts. Please see if there's any bugs or issues

**Comment by ChristianPomales** [comment]
Are all those imports in the package.json needed?

**Comment by jkwon045** [comment]
Can you make the circle outline thinner.

**Comment by JoePark1993** [comment]
No they are not. Thanks for checking! I'll make sure to uninstall the useless ones

**Comment by JoePark1993** [comment]
@jkwon045 I could but just for debugging purposes, I wanted to see THE THICK CIRCLE BECAUSE I HAD TO ZOOM OUT OF THE MAP TO SEE ITS GEOLOCATION

**Comment by JoePark1993** [comment]
@jkwon045  If you don't find any more issues feel free to merge!

**Pull request merged**
