### PR TITLE
Merge Backend into Master

### PR DESCRIPTION
**Pull request by ChristianPomales**
Would you guys mind looking over this real quick? Thanks!

### CODE REVIEW

**Comment by JoePark1993** [comment]
@ChristianPomales What fields should I be concerned about for my part? Is it related to what @vabdurahmanov is sending?

**Comment by ChristianPomales** [comment]
@JoePark1993 Mostly playerInfo and playerCount. Those are the functions that send you data 👍

**Comment by jkwon045** [comment]
Is there any other data I need to send to the backend? @ChristianPomales

**Comment by vabdurahmanov** [comment]
This is amazing.

**Comment by ChristianPomales** [comment]
@jkwon045 Not at the moment 👌

**Comment by JoePark1993** [comment]
@ChristianPomales ah perfect! Have you checked with @jkwon045? I believe she needs other stuff than that. @jkwon045 can you confirm?

**Comment by jkwon045** [comment]
I think for now this is everything I need. @JoePark1993 @ChristianPomales

**Pull request merged**
